[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
jogo-lottery = "CTMfMAsohXbSQa5TFTqFPpQdoQ88dUv77saWE1zXcrMq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/raytlty/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
