[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
jogo-lottery = "CTMfMAsohXbSQa5TFTqFPpQdoQ88dUv77saWE1zXcrMq"
jogo_vote = "62TKbRM9rPsUu5kKeGUkoqP5M4CyLiVSogfaVT1uJFLQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/raytlty/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init-jogo-state = "ts-node initialize/init_vote.ts"
init-jogo-lottery = "ts-node initialize/init_lottery.ts"
test-jogo-vote = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/jogo-vote.ts"
test-jogo-lottery = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/jogo-lottery.ts"
