[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
jogo-lottery = "BsEhRH3RcMmgjctKfH5KJd8yu2BYgvECZb2UEmZ2dPh1"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "https://devnet.sonic.game"
cluster = "Localnet"
wallet = "./.keypairs/deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init = "ts-node scripts/init_lottery.ts"