[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
jogo_vote = "62TKbRM9rPsUu5kKeGUkoqP5M4CyLiVSogfaVT1uJFLQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.sonic.game"
wallet = ".keypairs/deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init-jogo-state = "ts-node initialize/init_state.ts"
